// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service reads from and writes to the system clipboard via Win32 APIs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CopyFromForeground sends Ctrl+C to the foreground window via Win32 SendInput,
 * then waits 150 ms for the clipboard to be populated by the source app.
 * @returns {$CancellablePromise<void>}
 */
export function CopyFromForeground() {
    return $Call.ByID(239340991);
}

/**
 * PasteToForeground sends Ctrl+V to the foreground window via Win32 SendInput.
 * A 150 ms delay is applied first to let the clipboard write settle.
 * @returns {$CancellablePromise<void>}
 */
export function PasteToForeground() {
    return $Call.ByID(2319679526);
}

/**
 * Read returns the current clipboard text using the Win32 CF_UNICODETEXT format.
 * @returns {$CancellablePromise<string>}
 */
export function Read() {
    return $Call.ByID(52599179);
}

/**
 * Write stores text in the clipboard using CF_UNICODETEXT.
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function Write(text) {
    return $Call.ByID(608683786, text);
}
