// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service calls AI provider APIs from Go so the Wails WebView does not need
 * external network access (avoids WebKit content-security-policy issues on Linux).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Enhance sends text to the configured AI provider and returns the improved version.
 * @param {string} text
 * @returns {$CancellablePromise<string>}
 */
export function Enhance(text) {
    return $Call.ByID(1845763311, text);
}
