// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Provider holds credentials for a single AI provider.
 */
export class Provider {
    /**
     * Creates a new Provider instance.
     * @param {Partial<Provider>} [$$source = {}] - The source object to create the Provider.
     */
    constructor($$source = {}) {
        if (!("openai_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["openai_key"] = "";
        }
        if (!("claude_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["claude_key"] = "";
        }
        if (!("ollama_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ollama_url"] = "";
        }
        if (!("aws_region" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["aws_region"] = "";
        }
        if (!("aws_key_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["aws_key_id"] = "";
        }
        if (!("aws_secret" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["aws_secret"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Provider instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Provider}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Provider(/** @type {Partial<Provider>} */($$parsedSource));
    }
}

/**
 * Settings is the top-level application settings structure persisted to disk.
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("active_provider" in $$source)) {
            /**
             * "openai" | "claude" | "ollama" | "bedrock"
             * @member
             * @type {string}
             */
            this["active_provider"] = "";
        }
        if (!("providers" in $$source)) {
            /**
             * @member
             * @type {Provider}
             */
            this["providers"] = (new Provider());
        }
        if (!("shortcut_key" in $$source)) {
            /**
             * e.g. "ctrl+g"
             * @member
             * @type {string}
             */
            this["shortcut_key"] = "";
        }
        if (!("start_on_boot" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["start_on_boot"] = false;
        }
        if (!("theme_preference" in $$source)) {
            /**
             * "light" | "dark" | "system"
             * @member
             * @type {string}
             */
            this["theme_preference"] = "";
        }
        if (!("completed_setup" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["completed_setup"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField1_0($$parsedSource["providers"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Provider.createFrom;
