// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service handles loading and saving application settings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Get returns a copy of the current settings.
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function Get() {
    return $Call.ByID(1738358976).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Save persists the provided settings to disk.
 * @param {$models.Settings} updated
 * @returns {$CancellablePromise<void>}
 */
export function Save(updated) {
    return $Call.ByID(3456788065, updated);
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
