// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/wailsapp/wails/v3/pkg/application"
	"keylint/internal/features/clipboard"
	"keylint/internal/features/settings"
	"keylint/internal/features/shortcut"
	"keylint/internal/features/tray"
	"keylint/internal/features/welcome"
)

// Injectors from wire.go:

// InitializeApp is the Wire-generated constructor. Run `wire gen ./internal/app/`
// to produce wire_gen.go. The *application.App is provided externally.
func InitializeApp(wailsApp *application.App) (*App, error) {
	service, err := settings.NewService()
	if err != nil {
		return nil, err
	}
	welcomeService := welcome.NewService(service)
	shortcutService := provideShortcutService()
	clipboardService := clipboard.NewService()
	trayService := tray.NewService(wailsApp)
	app := &App{
		Settings:  service,
		Welcome:   welcomeService,
		Shortcut:  shortcutService,
		Clipboard: clipboardService,
		Tray:      trayService,
	}
	return app, nil
}

// wire.go:

// App bundles all top-level services needed to run KeyLint.
type App struct {
	Settings  *settings.Service
	Welcome   *welcome.Service
	Shortcut  shortcut.Service
	Clipboard *clipboard.Service
	Tray      *tray.Service
}

// provideShortcutService wraps the platform constructor for Wire.
func provideShortcutService() shortcut.Service {
	return shortcut.NewPlatformService()
}

var serviceSet = wire.NewSet(settings.NewService, welcome.NewService, clipboard.NewService, provideShortcutService)
