// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service reads from and writes to the system clipboard.
 * Uses xclip/xdotool on Linux, native Win32 via Go on Windows.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CopyFromForeground sends Ctrl+C to the currently focused window via xdotool,
 * then waits 150 ms for the clipboard to be populated.
 * @returns {$CancellablePromise<void>}
 */
export function CopyFromForeground() {
    return $Call.ByID(2818713757);
}

/**
 * PasteToForeground sends a Ctrl+V keystroke to the currently focused window.
 * Uses xdotool; intended to be called after writing fixed text to the clipboard
 * so the result is pasted back into the source application.
 * A 150 ms delay is applied first to let the clipboard write settle.
 * @returns {$CancellablePromise<void>}
 */
export function PasteToForeground() {
    return $Call.ByID(1965794476);
}

/**
 * Read returns the current clipboard text content.
 * @returns {$CancellablePromise<string>}
 */
export function Read() {
    return $Call.ByID(4016215765);
}

/**
 * Write sets the clipboard text content.
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function Write(text) {
    return $Call.ByID(2416338060, text);
}
