// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service handles first-run detection and setup completion.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CompleteSetup marks the setup wizard as done.
 * @returns {$CancellablePromise<void>}
 */
export function CompleteSetup() {
    return $Call.ByID(3562801053);
}

/**
 * IsFirstRun returns true if the user has not completed the setup wizard.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsFirstRun() {
    return $Call.ByID(3064530420);
}
